#!/usr/bin/env bash

touch "$BUILD/usr/lib/parallax-target/default/service-enable/"{ufw,NetworkManager} &&\
touch "$BUILD/usr/lib/parallax-user-target/boot/service-enable/"{pipewire,pipewire-pulse,wireplumber} \
	|| die "Failed to create target files!"
